use PortfolioProjects

select * from CovidDeaths

---
--DATA USEING FOR ANALYSIS
SELECT LOCATION,DATE,TOTAL_CASES,TOTAL_DEATHS,NEW_CASES,POPULATION
FROM CovidDeaths
ORDER BY 1,2

-- TOTAL DEATHS VS TOTAL CASES: DEATHPERCENTAGE

SELECT LOCATION,DATE, TOTAL_CASES, total_deaths, (CAST (TOTAL_DEATHS AS INT)/CAST (TOTAL_CASES AS INT))*100 AS DEATHPERCENTAGE
FROM CovidDeaths
WHERE LOCATION LIKE 'INDIA'
ORDER BY 1,2

 --TOTAL CASES VS TOTAL POPULATION: % OF POPULATION GOT COVID

SELECT LOCATION,DATE, population, TOTAL_CASES, (CAST (total_cases AS INT)/(population)*100 ) AS COVIDIMPACTED
FROM CovidDeaths
--WHERE LOCATION LIKE 'INDIA'
ORDER BY 1,2


--HIGH COVID INFECTED LOCATION
SELECT  LOCATION, POPULATION,MAX(CAST(TOTAL_CASES AS INT))  MAX_CASES, mAX(CAST (total_cases AS INT)/(population)*100 ) AS PERCENTAGE_INFECTED
FROM CovidDeaths
--WHERE location IN ('UNITED STATES','iNDIA', 'CHINA','ITALY','FRANCE','RUSSIA','UNITED kINGDOM')
GROUP BY location,POPULATION
ORDER BY PERCENTAGE_INFECTED DESC
--------------
--SELECT DATA WHERE COVIDIMPACTED RATE (TOTAL CASES % OVER TOTAL POPULATION) IS BETWEEN 10- 60%
SELECT LOCATION, MAX(CAST(TOTAL_CASES AS INT))  MAX_CASES, mAX(CAST (total_cases AS INT)/(population)*100 ) AS COVIDIMPACTED
FROM CovidDeaths
WHERE (CAST (total_cases AS INT)/(population)*100 ) BETWEEN 10 AND 60
GROUP BY location
ORDER BY 1 DESC
--------------------------
-- SELECT HIGH DEATH COUNT BY LOCATION
SELECT LOCATION, mAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT FROM CovidDeaths
WHERE CONTINENT IS NOT NULL
GROUP BY location
ORDER BY TOTALDEATHCOUNT DESC

----CONTINENT WITH HIGHEST DEATH COUNT
SELECT CONTINENT, mAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT FROM CovidDeaths
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TOTALDEATHCOUNT DESC


---GLOBAL NUMBERS- NEW CASES, NEW DEATHS, DEATH PERCENTAGE BASED ON DATE
SELECT SUM(NEW_CASES)AS TOTAL_NEWCASES,SUM(NEW_DEATHS) AS TOTAL_DEATHCOUNT,SUM(NEW_DEATHS)/SUM(NEW_CASES)*100 AS DEATHpERCENTAGE
FROM CovidDeaths
--WHERE CONTINENT IS NOT NULL
--GROUP BY DATE
ORDER BY 1,2
  
-------

--TOTAL POPULATION VS VACCINATION

SELECT CD.continent, CD.location,CD.date, CD.population, 
new_vaccinations, SUM(CONVERT(INT,NEW_VACCINATIONS)) OVER (PARTITION BY CD.LOCATION ORDER BY CD.LOCATION,CD.DATE) AS RUNNINGTOTALVACCINATIONCOUNT
FROM CovidDeaths CD
JOIN CovidVaccinations	CV
ON CD.date= CV.date
AND CD.location= CV.location
WHERE CD.continent IS NOT NULL
ORDER BY 2,3

-- USE CTE
WITH VACCINATIONRECORD (CONTINENT,LOCATION,DATE, POPULATION,NEW_VACCINATIONS,RUNNINGTOTALVACCINATIONCOUNT)
AS
(
SELECT CD.continent, CD.location, CD.date, CD.population, 
new_vaccinations, SUM(CONVERT(INT,NEW_VACCINATIONS)) OVER (PARTITION BY CD.LOCATION ORDER BY CD.LOCATION,CD.DATE) AS RUNNINGTOTALVACCINATIONCOUNT
FROM CovidDeaths CD
JOIN CovidVaccinations	CV
ON CD.date= CV.date
AND CD.location= CV.location
WHERE CD.continent IS NOT NULL)

SELECT *, (RUNNINGTOTALVACCINATIONCOUNT/POPULATION)*100 AS VACCINATION_POPULATION
FROM VACCINATIONRECORD

-- TEMP TABLE
DROP TABLE IF EXISTS #PERCENTPOPULATIONVACINATED
CREATE TABLE #PERCENTPOPULATIONVACINATED
(
CONTINENT NVARCHAR (50),
LOCATION NVARCHAR (250),
DATE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATION NUMERIC,
RUNNINGTOTALVACCINATIONCOUNT NUMERIC
)

INSERT INTO #PERCENTPOPULATIONVACINATED
SELECT CD.continent, CD.location, CD.date, CD.population, 
new_vaccinations, SUM(CONVERT(numeric,NEW_VACCINATIONS)) OVER (PARTITION BY CD.LOCATION ORDER BY CD.LOCATION,CD.DATE) AS RUNNINGTOTALVACCINATIONCOUNT
FROM CovidDeaths CD
JOIN CovidVaccinations	CV
ON CD.date= CV.date
AND CD.location= CV.location
--WHERE CD.continent IS NOT NULL

SELECT *, (RUNNINGTOTALVACCINATIONCOUNT/POPULATION)*100 AS VACCINATION_POPULATION
FROM #PERCENTPOPULATIONVACINATED
ORDER BY 1,2


---CREATING VIEWS
--VIEW 1 HIGH INFECTED LOCATION

CREATE VIEW HIGHLYINFECTED
AS
SELECT  LOCATION, POPULATION,MAX(CAST(TOTAL_CASES AS INT)) CASES, MAX(CAST (total_cases AS INT)/(population)*100 ) AS PERCENTAGE_INFECTED
FROM CovidDeaths
--WHERE location IN ('UNITED STATES','iNDIA', 'CHINA','ITALY','FRANCE','RUSSIA','UNITED kINGDOM')
GROUP BY location,POPULATION
--ORDER BY PERCENTAGE_INFECTED DESC

--- VIEW 2 %OFPOPULATIONVACCINATED

CREATE VIEW PECT_POPULATIONVACCINATED
AS
SELECT CD.continent, CD.location, CD.date, CD.population, 
new_vaccinations, SUM(CONVERT(numeric,NEW_VACCINATIONS)) OVER (PARTITION BY CD.LOCATION ORDER BY CD.LOCATION,CD.DATE) AS RUNNINGTOTALVACCINATIONCOUNT
FROM CovidDeaths CD
JOIN CovidVaccinations	CV
ON CD.date= CV.date
AND CD.location= CV.location
--WHERE CD.continent IS NOT NULL


--VIEW 3 GLOBAL_NUMBERS

CREATE VIEW GLOBAL_NUMBERS
AS
SELECT SUM(NEW_CASES)AS TOTAL_NEWCASES,SUM(NEW_DEATHS) AS TOTAL_DEATHCOUNT,SUM(NEW_DEATHS)/SUM(NEW_CASES)*100 AS DEATHpERCENTAGE
FROM CovidDeaths
WHERE CONTINENT IS NOT NULL
GROUP BY DATE
--ORDER BY 1,2

SELECT * FROM GLOBAL_NUMBERS